// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVH-8RUmnJ-WObsgiEMyZfeybecjflBqk',
    appId: '1:637656834263:web:e867090e0c118dddac1092',
    messagingSenderId: '637656834263',
    projectId: 'lpu-touch-36da9',
    authDomain: 'lpu-touch-36da9.firebaseapp.com',
    storageBucket: 'lpu-touch-36da9.firebasestorage.app',
    measurementId: 'G-72VGY3H8TP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGRov7rVhU5Wwxiyp6RuEQNO8kvvuTETQ',
    appId: '1:637656834263:android:2e6b766e47e463b1ac1092',
    messagingSenderId: '637656834263',
    projectId: 'lpu-touch-36da9',
    storageBucket: 'lpu-touch-36da9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVH-8RUmnJ-WObsgiEMyZfeybecjflBqk',
    appId: '1:637656834263:web:6ebd009f3954bcfaac1092',
    messagingSenderId: '637656834263',
    projectId: 'lpu-touch-36da9',
    authDomain: 'lpu-touch-36da9.firebaseapp.com',
    storageBucket: 'lpu-touch-36da9.firebasestorage.app',
    measurementId: 'G-BSVTPL7Y09',
  );
}
